### PR TITLE
Prefer variable syntax over function syntax over.

### PR DESCRIPTION
**Pull request by kkharji**
I don't know about you but I used to seeing that function syntax makes sense but after seeing other using the variable syntax and trying it, it actually made my code base less hard and easier to read and reason with. I couldn't find the right word to add to the this section, but a strong argument might be that Lua is based on the idea of tables, and often you see us defining a local table, setting default field values and exporting tables. It makes sense to used table syntax in lua for that reason.

### CODE REVIEW

**Comment by tarleb** [comment]
Interesting points, and thanks for bringing this up.

I think I partly agree, but I believe that there are more nuances to this. E.g., when defining a table that's used like a *class* in some OOP languages, then it can make sense to write

```lua
local MyStack = {items = {}}
function MyStack:push(x)
  table.insert(self.items, x)
end
function MyStack:pop()
  table.remove(self.items)
end
```
This allows to use the implicit parameter `self`, which can be handy.

However, if none of the functions in the table depends on the state of the table itself, then I agree that variable syntax is preferable.

**Comment by kkharji** [comment]
Well said @tarleb , I personally come from fp style so I didn't reach the level of oop in lua yet, although I can see how useful it powerful it can be.

How about we add a note about that and add  fourth example (that is the above), in which function syntax is better?

**Comment by tarleb** [comment]
Sounds good. Do you want to amend your PR?

**Comment by kkharji** [comment]
Sure, tom, or if you have time and energy. I'd appreciate it you amending it other wise tom first thing on my schedule :D GN

**Comment by tarleb** [comment]
Pushed a small change, will have to think a bit more about the remaining points.

**Pull request closed without merging**
